baseURL = 'https://robbredow.com/'
languageCode = 'en-us'
title = 'Rob Bredow'
theme = 'gerous'
#paginate = 9
pagination.pagerSize = 9

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

#-------------------------------
# General Site Settings

googleAnalytics = "" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Shows"
    url = "/categories/shows/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

 #[[menu.main]]
 #   name = "Publications"
 #   weight = 4
 #   hasChildren = true

 # [[menu.main]]
 #   parent = "Publications"
 #   name = "Solo"
 #   url = "/2019/04/making-solo-a-star-wars-story/"
 #   weight = 1

 # [[menu.main]]
 #   parent = "Publications"
 #   name = "Games"
 #   url = "/tags/games/"
 #   weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "About"
    url = "/about/"
    weight = 4


  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Get in touch"


[params]
  logo = "/images/robbredow-logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/robbredow-logo-dark.png"
  description = "Rob Bredow's Portfolio and Blog"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Author Settings
  [params.author]
    author_name = "Rob Bredow"
    author_avatar = "/images/rob-bredow-headshot-100x100.jpg"


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    #hero_title = "Hi! I'm a Producer & Creative Technology Executive who loves theme-driven design and creative teamwork."
    #hero_description = "I work at Lucasfilm and Industrial Light & Magic. Geek."
    hero_title = "Hi! I'm a Producer &<br/>Creative Tech Exec"
    hero_description = "I love theme-driven design and creative teamwork. Geek."

  [params.hero_logos]
    enable = true

  [[params.hero_logo_image]]
    image_alt = "Avengers End Game"
    image_url = "/images/hero/avengers-end-game.avif"

  [[params.hero_logo_image]]
    image_alt = "Cloudy with a Chance of Meatballs"
    image_url = "/images/hero/cloudy-with-a-chance-of-meatballs.avif"

  [[params.hero_logo_image]]
    image_alt = "Godzilla"
    image_url = "/images/hero/godzilla.avif"

  [[params.hero_logo_image]]
    image_alt = "Independence Day"
    image_url = "/images/hero/id4.avif"

  [[params.hero_logo_image]]
    image_alt = "Star Wars: Rise of Skywalker"
    image_url = "/images/hero/rise-of-skywalker.avif"

  [[params.hero_logo_image]]
    image_alt = "Solo: A Star Wars Story"
    image_url = "/images/hero/solo-a-star-wars-story.avif"

  [[params.hero_logo_image]]
    image_alt = "Stuart Little"
    image_url = "/images/hero/stuart-little.avif"

  [[params.hero_logo_image]]
    image_alt = "Surf's Up"
    image_url = "/images/hero/surfs-up.avif"

  [[params.hero_logo_image]]
    image_alt = "The Acolyte"
    image_url = "/images/hero/star-wars-acolyte-poster.avif"



  #-------------------------------
  # Slider Featured Settings
  [params.featured]
    enable = true
    featured_title = "Featured Shows"


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = false
    projects_title= "Recent Work"
    projects_description= ""

 #-------------------------------
  # About Section Settings
  [params.about_section]
    enable = true
    about_section_title = "Artist-Driven Innovation"
    about_section_description = "<a href=\"/2025/05/ted-artist-driven-innovation/\"<strong>We've been here before.</strong></a> Drawing on lessons from breakthroughs on <strong>Star Wars</strong> and <strong>Jurassic Park</strong>, this talk</a> focuses on artist-driven innovation in the age of AI. Rob has talked about creativity and <a href=\"/2018/08/on-creativity-theme-driven-design/\">theme-driven design</a> at <a href=\"https://www.ted.com/talks/rob_bredow_star_wars_changed_visual_effects_ai_is_doing_it_again\" target=\"_blank\">TED</a>, <a href=\"https://www.siggraph.org\" data-type=\"link\" data-id=\"https://www.siggraph.org\" target=\"_blank\">SIGGRAPH</a>, <a href=\"https://fmx.de/en/home\" data-type=\"link\" data-id=\"https://fmx.de/en/home\" target=\"_blank\">FMX</a>, <a href=\"http://www.viewconference.it\" data-type=\"link\" data-id=\"http://www.viewconference.it\" target=\"_blank\">VIEW</a> and others.</p>"
    about_section_image = "/images/2025/05/TED2025_20250408_2GT3204-medium.jpg"
    about_section_image_alt = "Rob Bredow at TED 2025"
    about_section_button_text = "Watch TED Talk"
    about_section_button_link = "/2025/05/ted-artist-driven-innovation/"

 #-------------------------------
  # Author Section Settings
  [params.author_section]
    enable = true
    author_section_title = "The Making of Solo:<br/> A Star Wars Story"
    author_section_description = "An intimate glimpse into the journey of the making of the film with stories from the first day of prep to the final days of post. Hundreds of never before seen photos."
    author_section_image = "/images/ILM-presents-Making-Solo-Star-Wars.avif"
    author_section_image_alt = "ILM Presents: Making Solo a Star Wars Story Book Cover"
    author_section_button_text = "Learn More..."
    author_section_button_link = "/2019/04/making-solo-a-star-wars-story/"
    author_section_button_text2 = "Buy Hardcover"
    author_section_button_link2 = "https://amzn.to/3KiyJFz"

    

  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonials_intro = "‚≠ê‚≠ê‚≠ê‚≠ê‚≠ê 4.7 Stars on Amazon"
    testimonials_title = "Some excerpts from reviewers..."
    testimonials_info = "<b><a href=https://www.starwars.com/news/rob-bredow-making-solo-book-interview>Learn more</a></b> about the book at <b><a href=https://www.starwars.com/news/rob-bredow-making-solo-book-interview>StarWars.com</a></b> or join these reviewers and <a href=https://amzn.to/3yLTtmv><b>buy your own copy now</b></a>..."

  [[params.testimonial_item]]
    name = "Marcin Janowski"
    image = "/images/marcin-janowski-120x120.jpg"
    designation = "Global Marketing"
    title = "Probably the best 'Making of' book in recent memory"
    content = "This book is an embarrassment of riches as far as the amount of photos included here. The images included here are special because - which along with their fly-on-the-wall descriptions have the power to inspire people to become storytellers."

  [[params.testimonial_item]]
    name = "Mrs Raven"
    image = "/images/mrs-raven-120x120.jpg"
    designation = "Amazon Review"
    title = "One Book, Three Stories"
    content = "This is an excellent addition to my collection. Takes a step back and tells the story of how movies are made. The location scouting, how effects are slipped into real locations, casting, and other processes that are relatable to any big movie. And finally, the pictures are spectacular. It is just like National Geographic!"

  [[params.testimonial_item]]
    name = "Steve Galloway"
    image = "/images/steve-galloway-120x120.jpg"
    designation = "Jedi News Network"
    title = "It takes us on a journey..."
    content = "Rob Bredow has created a book that well and truly gives you the feeling that it was created by someone from inside the production, not by other looking in. The stills used are at times very candid, humorous and others very serious, but it captures the passion and love that the creative teams and actors poured into the movie."

  [[params.testimonial_item]]
    name = "Matt Rushing"
    image = "/images/matt-rushing-120x120.jpg"
    designation = "Trek.fm Podcast Host"
    title = "I encourage you to pick up a copy"
    content = "There have been a lot of ‚Äúmaking of‚Äù books for Star Wars movies, but none have ever felt this intimate. Bredow‚Äôs photos are as behind the scenes as it gets, raw and completely in the moment. He captures the essence of what it is like to be on set. His daughter‚Äôs interview with DP Bradford Young for a school project illustrates how Star Wars truly is a family affair, even for those behind the camera."


  #-------------------------------
  # Faq (Frequently asked questions) Settings
  [params.faq]
    enable = true
    faq_intro = "Need some answers?"
    faq_title = "Frequently asked questions"

  [[params.faq_item]]
    title = "This sounds fun, are you hiring?"
    description = "Yes! We are almost always hiring at ILM. Check <b><a href=\"https://ilm.com/careers/\">ILM.com/careers</a></b> for the latest info and browse the posted positions in our studios around the world."

  [[params.faq_item]]
    title = "Can I send you a Star Wars idea or a script?"
    description = "No. As an employee of Lucasfilm I cannot receive unsolicited pitches. Sorry."

  [[params.faq_item]]
    title = "I'd like to study to work in the entertainment industry, what roles should I consider?"
    description = "Check out <b><a href=\"https://gitd.lucasfilm.com/\">Get In the Door</a></b> for interviews with a number of people in a wide variety of positions at Lucasfilm and Industrial Light & Magic. I think you may find someone there who inspires you."

  [[params.faq_item]]
    title = "How can I contribute to software used by the entertainment industry?"
    description = "The Academy Software Foundation is an open source, non-profit organization dedicated to getting people involved in a healthy software ecosytem for filmmaking, many of our projects focus on visual-effects and animation. I recommend checking out <b><a href=\"https://www.aswf.io/\">ASWF.io</a></b> to learn more and get involved as it's a great way to meet people working in the industry and find a passion project to contribute to."

  [[params.faq_item]]
    title = "Can we collaborate on a speaking engagement or photography project together?"
    description = "Please reach out, I'd love to talk with you. My job at Lucasfilm means I'm not always available, but I always love to hear about opportunities to work on something creative together."
    

  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog_intro = "What‚Äôs new?"
    blog_title = "Latest from blog"



  #-------------------------------
  # Footer Settings

  # Social Links

  [[params.social]]
    icon = "fa-brands fa-imdb"
    name = "IMDB"
    link = "https://www.imdb.com/name/nm0106650/"

  [[params.social]]
    icon = "fa-brands fa-linkedin"
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/robbredow/"

  [[params.social]]
    icon = "fa-brands fa-instagram"
    name = "Instagram"
    link = "https://instagram.com/rbredow"

  [[params.social]]
    icon = "fa-solid fa-podcast"
    name = "Lighter Darker: The ILM Podcast"
    link = "https://www.ilm.com/lighterdarker/"

  [[params.social]]
    icon = "fa-brands fa-threads"
    name = "Threads"
    link = "https://www.threads.net/@rbredow"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com/rbredow"


  # Other icons can be found at https://fontawesome.com/icons


  # Newsletter
  [params.mailchimp]
    enable = false
    mailchimp_title = "Stay inspired weekly üì¨ Your friendly dose of tips & insights!"
    mailchimp_description = "Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox."
    mailchimp_identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp_input_text = "Your email address"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "mblrroop" # Add your form_id

    # NOTE
    # Gerous comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "robbredow-com" # Add your shortname for Disqus Comment. 
